package kz.agrosfera.app.domain.plant

object PlantDiseaseCatalog {
    val diseases: List<PlantDisease> = listOf(
        PlantDisease(
            id = "tomato_late_blight",
            categoryId = "tomato",
            name = "Фитофтороз",
            summary = "Ылғалды кезде жапырақ пен жемісте қоңыр-қара шірін.",
            symptoms = "Жапырақ шеттерінен басталатын дақтар, ылғалда жылдам таралу, жеміс шірігі.",
            prevention = "Төселмемен ылғалды азайтыңыз.\nТам drip суару қолданыңыз.\nПрофилактикалық фунгицид жоспары.\nАуру өсімдіктерін оқшаулаңыз.",
            frequencyRank = 1,
        ),
        PlantDisease(
            id = "tomato_early_blight",
            categoryId = "tomato",
            name = "Альтернариоз",
            summary = "Концентрлік дақтар, құрғақ аймақтар.",
            symptoms = "Қара дақтар сақиналы құрылыммен, төменгі жапырақтарда көп.",
            prevention = "Резервуарды тазарту.\nФунгицидтік профилактика.\nТығыздықты азайту.",
            frequencyRank = 2,
        ),
        PlantDisease(
            id = "tomato_septoria",
            categoryId = "tomato",
            name = "Септориоз",
            summary = "Жапырақта сары дақтар мен қара нүктелер.",
            symptoms = "Төменгі жапырақтарда сары дақтар, кейін қара пустулалар, жапырақ құлауы.",
            prevention = "Резервуарды тазартыңыз.\nЗақымдалған жапырақтарды жойыңыз.\nРұқсат етілген фунгицидтермен уақытылы емдеңіз.\nӨсімдіктер арасында желдетуді жақсартыңыз.",
            frequencyRank = 3,
        ),
        PlantDisease(
            id = "tomato_bacterial_spot",
            categoryId = "tomato",
            name = "Бактериялық дақ",
            summary = "Дәнделі дақтар, сулы шекара.",
            symptoms = "Кіші дөңес дақтар, жапырақ тесілуі, жемісте дақ.",
            prevention = "Таза тұқым.\nСуруды таңертең жүргізу.\nМыс препараттары (нұсқаулық бойынша).\nЗақымдалған бөліктерді жою.",
            frequencyRank = 4,
        ),
        PlantDisease(
            id = "tomato_mosaic",
            categoryId = "tomato",
            name = "Вирустық мозаика",
            summary = "Түсті мозаика, өсу баяулады.",
            symptoms = "Сары-жасыл дақтар, жапырақ бұрылуы, өнім азайуы.",
            prevention = "Зиянкестерді бақылау (өткізгіштер).\nҚолмен жұмыс алдында дезинфекция.\nАуру тұқымын пайдаланбау.",
            frequencyRank = 5,
        ),
        PlantDisease(
            id = "cucumber_powdery_mildew",
            categoryId = "cucumber",
            name = "Ұnтақ саңыraуқұlaқ",
            summary = "Жapыraқta aq untaq tәрізді jabın.",
            symptoms = "Жapыraқ pen sabaqta aq qabat, büktelu, fotosintez tөmendeui.",
            prevention = "Tıǵyz otırǵyzbau.\nTünimen ilǵaldy azaytu.\nSulfurli nemese biologiyalyq preparattar.",
            frequencyRank = 1,
        ),
        PlantDisease(
            id = "cucumber_downy_mildew",
            categoryId = "cucumber",
            name = "Кек саңыraуқұlaқ",
            summary = "Жapыraқ astında sary-syr jabın.",
            symptoms = "Жapыraқ üstinde sary dаqtar, astında syr jabın, japıraқ quraу.",
            prevention = "Jelдетudi jaqsartu.\nTam drip suaru.\nFungitsid.",
            frequencyRank = 2,
        ),
        PlantDisease(
            id = "cucumber_anthracnose",
            categoryId = "cucumber",
            name = "Антракноз",
            summary = "Жemiste qoңyr dаqtar.",
            symptoms = "Dөnges dаqtar, shiriп ketu, japıraқta dаqtar.",
            prevention = "Rezervuardy tazalau.\nAury jemisterdi joiu.",
            frequencyRank = 3,
        ),
        PlantDisease(
            id = "cucumber_angular_spot",
            categoryId = "cucumber",
            name = "Бактериялық бұрышты дақ",
            summary = "Жapыraқta buryshty sary dаqtar.",
            symptoms = "Su shekaraly dаqtar, japıraқ dyrily.",
            prevention = "Taza tukym.\nSu bryngdau.\nMis preparattary.",
            frequencyRank = 4,
        ),
        PlantDisease(
            id = "potato_late_blight",
            categoryId = "potato",
            name = "Фитофтороз",
            summary = "Kartopta eń qauipti aury, ылғalda tez taralady.",
            symptoms = "Жapыraқta qoңyr dаqtar, aq mitseliy, klubnede shiriп.",
            prevention = "Sapaly tukym.\nAury klubnelerdi joiu.\nProfilaktikalyq fungitsid.",
            frequencyRank = 1,
        ),
        PlantDisease(
            id = "potato_scab",
            categoryId = "potato",
            name = "Картоп қabық дақ",
            summary = "Klubnede qabyqta dаqtar men oйыklar.",
            symptoms = "Klubnede qoңyr dаqtar, qabyq buzylu, saqtau qiyin.",
            prevention = "Topıraq pH baqylau.\nAuyspaly egis.\nRezistentti sorttar.",
            frequencyRank = 2,
        ),
        PlantDisease(
            id = "potato_fusarium",
            categoryId = "potato",
            name = "Фузариоз",
            summary = "Tamir men sabaqta shiriп, sarğayu.",
            symptoms = "Sabaq ishinde qoңyr jolak, japıraқ sarğayu, erteroq qulau.",
            prevention = "Topıraq dezinfektsiya.\nSu retteu.\nTukym öngdeu.\nAuyspaly egis.",
            frequencyRank = 3,
        ),
        PlantDisease(
            id = "potato_blackleg",
            categoryId = "potato",
            name = "Қara ayaq",
            summary = "Sabaq tübi qarau, ösimdik quraу.",
            symptoms = "Sabaq tübi qara, is, klubne önimi azayady.",
            prevention = "Sertifikatty tukym.\nTaza topıraq.\nAury ösimdikterdi joiu.",
            frequencyRank = 4,
        ),
        PlantDisease(
            id = "pepper_bacterial_spot",
            categoryId = "pepper",
            name = "Бактериялық дақ",
            summary = "Жapыraқ pen жemiste su dаqtar.",
            symptoms = "Kishi dөnges dаqtar, japıraқ tesilui, жemiste qabyq dаqtar.",
            prevention = "Taza tukym.\nSu bryngdau.\nZaqym bolekterdi joiu.",
            frequencyRank = 1,
        ),
        PlantDisease(
            id = "pepper_anthracnose",
            categoryId = "pepper",
            name = "Антракноз",
            summary = "Жemiste shiriп ketu, dөnges dаqtar.",
            symptoms = "Qoңyr oйыq dаqtar, shiriп ketu, japıraқta dаqtar.",
            prevention = "Rezervuardy tazalau.\nFungitsid.\nZaqym jemisterdi joiu.",
            frequencyRank = 2,
        ),
        PlantDisease(
            id = "pepper_mosaic",
            categoryId = "pepper",
            name = "Вирустық мозаика",
            summary = "Tusti mozaika, ösu bayaulady.",
            symptoms = "Sary-jasyl dаqtar, burtalu, önim azayu.",
            prevention = "Ziyankesterdi baqylau.\nDezinfektsiya.\nAury tukymyn qoldanbau.",
            frequencyRank = 3,
        ),
        PlantDisease(
            id = "apple_scab",
            categoryId = "apple",
            name = "Қara дақ",
            summary = "Жapыraқ pen жemiste qara dаqtar.",
            symptoms = "Qara-zeyil dаqtar, жemiste qabyq dаqtar, erteroq tusu.",
            prevention = "Tazalau.\nFungitsidtik profilaktika.\nRezistent sort.",
            frequencyRank = 1,
        ),
        PlantDisease(
            id = "apple_rust",
            categoryId = "apple",
            name = "Шіркеу",
            summary = "Жapыraқ astında sary dаqtar, üstinde zeng nükte.",
            symptoms = "Pustulalar, japıraқ sarğayu, erteroq qulau.",
            prevention = "Auyspaly egis.\nRezervuardy tazalau.\nFungitsid.",
            frequencyRank = 2,
        ),
        PlantDisease(
            id = "apple_fire_blight",
            categoryId = "apple",
            name = "От шелегі",
            summary = "Salqyn quraу, qara sabaq uшteri.",
            symptoms = "Sabaq qarau, gul quraу, tez taralu.",
            prevention = "Zaqym bolekterdi kesu.\nSort tanau.\nAntibakterial öngdeu.",
            frequencyRank = 3,
        ),
        PlantDisease(
            id = "grape_downy_mildew",
            categoryId = "grape",
            name = "Кек саңыraуқұlaқ",
            summary = "Жapыraқ astında sary-syr jabın.",
            symptoms = "Sary dаqtar, syr jabın, gul quraу.",
            prevention = "Jelдетu.\nFungitsid.\nRezervuardy tazalau.",
            frequencyRank = 1,
        ),
        PlantDisease(
            id = "grape_powdery_mildew",
            categoryId = "grape",
            name = "Ұnтаq saңyrauqulaq",
            summary = "Aq untaq jabın japıraқta.",
            symptoms = "Aq qabat, büktelu, sharbayu azayu.",
            prevention = "Tıǵyzdıq azaytu.\nSulfurli preparat.\nKesip tazalau.",
            frequencyRank = 2,
        ),
        PlantDisease(
            id = "grape_black_rot",
            categoryId = "grape",
            name = "Қara shiriп",
            summary = "Жemiste qara shiriп, dаqtar.",
            symptoms = "Qara dаqtar, shiriп ketu, japıraқta dаqtar.",
            prevention = "Zaqym jemisterdi joiu.\nFungitsid.\nTazalau.",
            frequencyRank = 3,
        ),
        PlantDisease(
            id = "cabbage_clubroot",
            categoryId = "cabbage",
            name = "Tübir qubırlanu",
            summary = "Tübirde qubırlar, ösimdik quraу.",
            symptoms = "Tübir qubırlanu, sarğayu, ösu toqtau.",
            prevention = "Auyspaly egis.\nTopıraq qizyq.\nRezistent sort.",
            frequencyRank = 1,
        ),
        PlantDisease(
            id = "cabbage_black_rot",
            categoryId = "cabbage",
            name = "Қara shiriп",
            summary = "Жapыraқ shetinde sary dаqtar, qara shiriп.",
            symptoms = "V-tәrizi dаqtar, qara shiriп, is.",
            prevention = "Taza tukym.\nZaqym bolekterdi joiu.\nAuyspaly egis.",
            frequencyRank = 2,
        ),
        PlantDisease(
            id = "cabbage_downy_mildew",
            categoryId = "cabbage",
            name = "Кек саңыraуқұlaқ",
            summary = "Жapыraқ astında syr jabın.",
            symptoms = "Sary dаqtar, japıraқ quraу.",
            prevention = "Jelдетu.\nIlǵaldy azaytu.\nFungitsid.",
            frequencyRank = 3,
        ),
        PlantDisease(
            id = "carrot_leaf_blight",
            categoryId = "carrot",
            name = "Альтернариоз",
            summary = "Жapыraқta qoңyr dаqtar.",
            symptoms = "Qoңyr-sary dаqtar, japıraқ quraу, tübir ösimi bayaulady.",
            prevention = "Rezervuardy tazalau.\nTukym öngdeu.\nAuyspaly egis.",
            frequencyRank = 1,
        ),
        PlantDisease(
            id = "carrot_root_rot",
            categoryId = "carrot",
            name = "Tübir shiriп",
            summary = "Tübir ichinde shiriп.",
            symptoms = "Tübir jumysqa jaramsyz, qoңyr shiriп, is.",
            prevention = "Su retteu.\nTopıraq drenaj.\nZaqym tukym joiu.",
            frequencyRank = 2,
        ),
        PlantDisease(
            id = "carrot_mosaic",
            categoryId = "carrot",
            name = "Вирустық мозаика",
            summary = "Tusti mozaika, ösu bayaulady.",
            symptoms = "Sary-jasyl dаqtar, japıraқ burtalu.",
            prevention = "Ziyankesterdi baqylau.\nTaza tukym.\nDezinfektsiya.",
            frequencyRank = 3,
        ),
    )

    fun byId(id: String): PlantDisease? = diseases.firstOrNull { it.id == id }

    fun byCategory(categoryId: String): List<PlantDisease> =
        diseases.filter { it.categoryId == categoryId }.sortedBy { it.frequencyRank }
}
